# Generated by Django 5.2.15 on 2026-07-07 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام فرستنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('unread', 'خوانده نشده'), ('read', 'خوانده شده')], default='unread', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان (فارسی)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_fa', models.TextField(verbose_name='توضیحات کوتاه (فارسی)')),
                ('description_en', models.TextField(verbose_name='Short Description (English)')),
                ('long_description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل (فارسی)')),
                ('long_description_en', models.TextField(blank=True, null=True, verbose_name='Long Description (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='تصویر پروژه')),
                ('tech_stack', models.JSONField(default=list, verbose_name='تکنولوژی\u200cهای استفاده شده')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='لینک دمو')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='لینک سورس\u200cکد')),
                ('category', models.CharField(choices=[('web', 'وبسایت / Web App'), ('mobile', 'اپلیکیشن موبایل / Mobile App'), ('ai', 'هوش مصنوعی / AI & Data Science'), ('design', 'طراحی و رابط کاربری / UI/UX Design'), ('other', 'سایر / Other')], default='web', max_length=50, verbose_name='دسته\u200cبندی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('featured', models.BooleanField(default=False, verbose_name='پروژه ویژه')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=150, verbose_name='عنوان خدمت (فارسی)')),
                ('title_en', models.CharField(max_length=150, verbose_name='Service Title (English)')),
                ('description_fa', models.TextField(verbose_name='توضیحات (فارسی)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('icon', models.CharField(default='Code', max_length=50, verbose_name='نام آیکون (Lucide)')),
                ('price_fa', models.CharField(blank=True, max_length=100, null=True, verbose_name='قیمت (فارسی)')),
                ('price_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price (English)')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید تنظیمات')),
                ('value', models.JSONField(verbose_name='مقدار تنظیمات (JSON)')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=150, verbose_name='نام (فارسی)')),
                ('name_en', models.CharField(max_length=150, verbose_name='Name (English)')),
                ('role_fa', models.CharField(max_length=150, verbose_name='نقش (فارسی)')),
                ('role_en', models.CharField(max_length=150, verbose_name='Role (English)')),
                ('bio_fa', models.TextField(blank=True, null=True, verbose_name='بیوگرافی (فارسی)')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Bio (English)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='لینک گیت\u200cهاب')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name_fa', models.CharField(max_length=150, verbose_name='نام مشتری (فارسی)')),
                ('client_name_en', models.CharField(max_length=150, verbose_name='Client Name (English)')),
                ('client_company_fa', models.CharField(blank=True, max_length=150, null=True, verbose_name='شرکت/برند مشتری (فارسی)')),
                ('client_company_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Client Company (English)')),
                ('client_avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر مشتری')),
                ('feedback_fa', models.TextField(verbose_name='بازخورد (فارسی)')),
                ('feedback_en', models.TextField(verbose_name='Feedback (English)')),
                ('rating', models.IntegerField(default=5, verbose_name='امتیاز (۱ تا ۵)')),
                ('approved', models.BooleanField(default=False, verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=250, verbose_name='عنوان مقاله (فارسی)')),
                ('title_en', models.CharField(max_length=250, verbose_name='Article Title (English)')),
                ('content_fa', models.TextField(verbose_name='محتوا (فارسی)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر کاور')),
                ('tags', models.JSONField(default=list, verbose_name='تگ\u200cها')),
                ('views_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='اسلاگ (URL-friendly)')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
